import React from "react";
import Sidebar from "../../components/Sidebar";
import Head from "next/head";

const Documentation = (props) => {
  return (
    <>
      <Sidebar load={props.query.newdata} />
      <Head>
        <title>{props.query.newdata}-OpenAI API</title>
        <meta name="description" content="Generated by Aditya" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export async function getServerSideProps({ query }) {
  return { props: { query: query } };
}
export default Documentation;
