import React from "react";
import Sidebar from "../components/Sidebar";
import Head from "next/head";

const Documentation = () => {
  return (
    <>
      <Sidebar />
      <Head>
        <title>Documentation-OpenAI API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Documentation;
